Add 0x in some error messages
In test fillers and test files, state roots are expected to contain the 0x prefix.
This commit adds such prefixes in error messages so that it's easier to edit the test files using the error messages.

For example,
```
test/tools/libtesteth/ImportTest.cpp(640): error: in "StateTestsGeneral/stExample": add11 on Byzantium: Expected another postState hash! expected: 0x07454a767e5f04461256f3812ffca930443c04a47d05ce3f38940c4a14b8c479 actual: 17454a767e5f04461256f3812ffca930443c04a47d05ce3f38940c4a14b8c479 in Byzantium data: 0 gas: 0 val: 0
```
becomes
```
test/tools/libtesteth/ImportTest.cpp(640): error: in "StateTestsGeneral/stExample": add11 on Byzantium: Expected another postState hash! expected: 0x07454a767e5f04461256f3812ffca930443c04a47d05ce3f38940c4a14b8c479 actual: 0x17454a767e5f04461256f3812ffca930443c04a47d05ce3f38940c4a14b8c479 in Byzantium data: 0 gas: 0 val: 0
```